api: 1.8.8-R0.1-SNAPSHOT
api-version: "1.8.8"
main: com.buha007.thepit.main.Main
name: ThePit
version: "1.2.0"
author: Bufnita
commands:
  thepit:
    description: ThePit main command
    usage: /thepit <args>